services:
  postgres:
    image: postgres:17-alpine
    container_name: matchpet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - matchpet_postgres_data:/var/lib/postgresql/data

volumes:
  matchpet_postgres_data:
